#----------------------------------------------------------------------
# This file was generated by encode_bitmaps.py
#
import tkinter as tk

def getNewData():
    return  '''
    R0lGODlhEAAQALMAAAAAAP//AP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAA\nAAAAACH5BAEAAAIALAAAAAAQABAAQAQ3UMgpAKC4hm13uJnWgR
    TgceZJllw4pd2Xpagq0WfeYrD7\n2i5Yb+aJyVhFHAmnazE/z4tlSq0KIgA7\n
'''

def getNewBitmap():
    return tk.PhotoImage(data=getNewData())
    

def getNewImage():
    return tk.PhotoImage(data=getNewData())

